import os
from PIL import Image

"""
Go to the output folders generated by HoverNet inference prediction and copy the file of interest to the
previous directory in the tree structure changing the name of the file in the desired format.

"""
imageofinterest = 'instances.png'  # can be overlay.png or instances.png in the case

Outputdir = '/home/lsancere/These/CMMC/Local_DATA/HoverNet_DATA/Predictions/Outputs_sample_006_all_instances/'

for root, dirs, files in os.walk(Outputdir):
    newname = root + '.png'
    if files != [] and os.path.exists(newname) == False and root != Outputdir:
        imagepath = root + '/' + imageofinterest
        image = Image.open(imagepath)
        image.save(newname)
        print('image saved :', newname)
